language: python
python:
  - 3.8
install:
  - pip install numpy
  - pip install matplotlib
  - pip install torch
  - pip install Pillow
  - pip install urllib3
script:
  - pytest
  - python setup.py bdist_wheel
